name: release

on:
  release:
    types:
      - published

jobs:
  goreleaser:
    name: upload binaries
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          fetch-depth: 0

      - uses: sigstore/cosign-installer@1b9f7b6d8b33e3d8bdd45d340515c318619cd481 # v3.0.2

      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v3.3.1
        with:
          go-version: 1.19
          cache: true

      - uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b # v4.2.0
        with:
          distribution: goreleaser
          version: latest
          # NOTE: we use parallelism 1 because the cosign process is not concurrency safe.
          args: release --parallelism 1 --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.TFLIBSONNET_CI_GITHUB_TOKEN }}
          COSIGN_EXPERIMENTAL: true
