name: release

on:
  release:
    types:
      - published

jobs:
  goreleaser:
    name: upload binaries
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          fetch-depth: 0

      - uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b # v2.8.1

      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v3.3.1
        with:
          go-version: 1.19
          cache: true

      - uses: goreleaser/goreleaser-action@9754a253a8673b0ea869c2e863b4e975497efd0c # v4.1.1
        with:
          distribution: goreleaser
          version: latest
          # NOTE: we use parallelism 1 because the cosign process is not concurrency safe.
          args: release --parallelism 1 --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.TFLIBSONNET_CI_GITHUB_TOKEN }}
          COSIGN_EXPERIMENTAL: true
